package CLDR::Number::Data;

use v5.8.1;
use utf8;
use strict;
use warnings;
use charnames qw( :full );

our $VERSION      = '0.00';
our $CLDR_VERSION = '24';

# XXX: data for testing
our $NUMBERS = {
    root => {
        default_number_system     => 'latn',
        other_number_systems      => { native => 'latn' },
        decimal_sign              => '.',
        group_sign                => ',',
        list_sign                 => ';',
        percent_sign              => '%',
        plus_sign                 => '+',
        minus_sign                => '-',
        exponent_sign             => 'E',
        superscript_exponent_sign => '×',
        per_mille_sign            => '‰',
        infinity_sign             => '∞',
        nan_sign                  => 'NaN',
        decimal_pattern           => '#,##0.###',
        scientific_pattern        => '#E0',
        percent_pattern           => '#,##0%',
        currency_pattern          => '¤ #,##0.00',
        at_least_pattern          => '⩾{0}',
        range_pattern             => '{0}–{1}',
    },
    ar => {
        default_number_system => 'arab',
        other_number_systems  => { native => 'arab' },
        decimal_sign          => '٫',
        group_sign            => '٬',
        list_sign             => '؛',
        percent_sign          => '٪',
        plus_sign             => "\N{RIGHT-TO-LEFT MARK}+",
        minus_sign            => "\N{RIGHT-TO-LEFT MARK}-",
        exponent_sign         => 'ﺎﺳ',
        per_mille_sign        => '؉',
        nan_sign              => 'ﻞﻴﺳ ﺮﻘﻣ',
        currency_pattern      => '¤ #,##0.00',
        at_least_pattern      => '+{0}',
    },
    en => {
        currency_pattern   => '¤#,##0.00;(¤#,##0.00)',
        at_least_pattern   => '{0}+',
    },
    fr => {
        decimal_sign       => ',',
        group_sign         => ' ',
        percent_pattern    => '#,##0 %',
        currency_pattern   => '#,##0.00 ¤;(#,##0.00 ¤)',
        at_least_pattern   => 'au moins {0}',
        range_pattern      => 'de {0} à {1}',
    },
    in => {
        decimal_pattern    => '#,##,##0.###',
        percent_pattern    => '#,##,##0%',
        currency_pattern   => '¤ #,##,##0.00',
    },
};

our $CURRENCIES = {
    root => {
        AUD => 'A$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    cs => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    da => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'kr',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    de => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    en => {
        AUD => 'A$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    es => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => 'GBP',
        JPY => 'JPY',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    fi => {
        AUD => 'AUD',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    fr => {
        AUD => '$AU',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£GB',
        JPY => '¥JP',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$US',
    },
    hu => {
        AUD => 'AUD',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => 'EUR',
        GBP => 'GBP',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    it => {
        AUD => 'A$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    ja => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '￥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    ko => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    nb => {
        AUD => 'AUD',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JPY',
        NOK => 'kr',
        SEK => 'SEK',
        USD => 'USD',
    },
    nl => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    pl => {
        AUD => 'AUD',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => 'GBP',
        JPY => 'JPY',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'USD',
    },
    pt => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    ru => {
        AUD => 'A$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    sv => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'Dkr',
        EUR => '€',
        GBP => 'GB£',
        JPY => 'JP¥',
        NOK => 'NKr',
        SEK => 'kr',
        USD => 'US$',
    },
    th => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    tr => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    zh => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
};

1;
