package CLDR::Number::Data;

use v5.8.1;
use utf8;
use strict;
use warnings;
use charnames qw( :full );

our $VERSION      = '0.00';
our $CLDR_VERSION = '24';

# XXX: data for testing
our $NUMBERS = {
    root => {
        patterns => {
            atLeast => '⩾{0}',
            currency => '¤ #,##0.00',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}–{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => '.',
            exponential => 'E',
            group => ',',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    cs => {
        patterns => {
            atLeast => '{0}+',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0 %',
            range => '{0}–{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    da => {
        patterns => {
            atLeast => '{0} eller derover',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0 %',
            range => '{0}-{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => '.',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    de => {
        patterns => {
            atLeast => '{0}+',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0 %',
            range => '{0}–{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => '.',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '·',
        },
    },
    en => {
        patterns => {
            atLeast => '{0}+',
            currency => '¤#,##0.00',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}–{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => '.',
            exponential => 'E',
            group => ',',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    es => {
        patterns => {
            atLeast => 'Más de {0}',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}-{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    fi => {
        patterns => {
            atLeast => 'vähintään {0}',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0 %',
            range => '{0}‒{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '−',
            nan => 'epäluku',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    fr => {
        patterns => {
            atLeast => 'au moins {0}',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0 %',
            range => 'de {0} à {1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    hu => {
        patterns => {
            atLeast => '{0}+',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}–{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    it => {
        patterns => {
            atLeast => '{0}+',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}-{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => '.',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    ja => {
        patterns => {
            atLeast => '{0} 以上',
            currency => '¤#,##0.00',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}～{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => '.',
            exponential => 'E',
            group => ',',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    ko => {
        patterns => {
            atLeast => '{0}+',
            currency => '¤#,##0.00;(¤#,##0.00)',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}-{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => '.',
            exponential => 'E',
            group => ',',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    nb => {
        patterns => {
            atLeast => '⩾{0}',
            currency => '¤ #,##0.00',
            decimal => '#,##0.###',
            percent => '#,##0 %',
            range => '{0}‒{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '−',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    nl => {
        patterns => {
            atLeast => '{0}+',
            currency => '¤ #,##0.00;¤ #,##0.00-',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}-{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => '.',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    pl => {
        patterns => {
            atLeast => '{0}+',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}–{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    pt => {
        patterns => {
            atLeast => '+{0}',
            currency => '¤#,##0.00',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}–{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => '.',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    ru => {
        patterns => {
            atLeast => '{0}+',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0 %',
            range => '{0}-{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'не число',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    sv => {
        patterns => {
            atLeast => '⩾{0}',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '#,##0 %',
            range => '{0}‒{1}',
            scientific => '#E0',
        },
        symbols => {
            currencyDecimal => ':',
            decimal => ',',
            exponential => '×10^',
            group => ' ',
            infinity => '∞',
            list => ';',
            minusSign => '−',
            nan => '¤¤¤',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '·',
        },
    },
    th => {
        patterns => {
            atLeast => '{0}+',
            currency => '¤#,##0.00',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}-{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => '.',
            exponential => 'E',
            group => ',',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    tr => {
        patterns => {
            atLeast => '{0}+',
            currency => '#,##0.00 ¤',
            decimal => '#,##0.###',
            percent => '%#,##0',
            range => '{0}–{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => ',',
            exponential => 'E',
            group => '.',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
    zh => {
        patterns => {
            atLeast => '{0}+',
            currency => '¤ #,##0.00',
            decimal => '#,##0.###',
            percent => '#,##0%',
            range => '{0}-{1}',
            scientific => '#E0',
        },
        symbols => {
            decimal => '.',
            exponential => 'E',
            group => ',',
            infinity => '∞',
            list => ';',
            minusSign => '-',
            nan => 'NaN',
            perMille => '‰',
            percentSign => '%',
            plusSign => '+',
            superscriptingExponent => '×',
        },
    },
};

our $CURRENCIES = {
    cs => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    da => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'kr',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    de => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    en => {
        AUD => 'A$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    es => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => 'GBP',
        JPY => 'JPY',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    fi => {
        AUD => 'AUD',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    fr => {
        AUD => '$AU',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£GB',
        JPY => '¥JP',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$US',
    },
    hu => {
        AUD => 'AUD',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => 'EUR',
        GBP => 'GBP',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    it => {
        AUD => 'A$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    ja => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '￥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    ko => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    nb => {
        AUD => 'AUD',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JPY',
        NOK => 'kr',
        SEK => 'SEK',
        USD => 'USD',
    },
    nl => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    pl => {
        AUD => 'AUD',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => 'GBP',
        JPY => 'JPY',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'USD',
    },
    pt => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    ru => {
        AUD => 'A$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    sv => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'Dkr',
        EUR => '€',
        GBP => 'GB£',
        JPY => 'JP¥',
        NOK => 'NKr',
        SEK => 'kr',
        USD => 'US$',
    },
    th => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
    tr => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => '¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => '$',
    },
    zh => {
        AUD => 'AU$',
        CHF => 'CHF',
        DKK => 'DKK',
        EUR => '€',
        GBP => '£',
        JPY => 'JP¥',
        NOK => 'NOK',
        SEK => 'SEK',
        USD => 'US$',
    },
};

1;
